export const config = { runtime: 'nodejs' };
function setCORS(res){ try{ res.setHeader('Access-Control-Allow-Origin','*'); res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS'); res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization'); }catch{} }
function clamp(n,min,max){ return Math.min(max, Math.max(min,n)); }
function num(x){ const n=Number(x); return Number.isFinite(n)?n:NaN; }
function sanitizeMetrics(m){ let bodyLenToHeight=num(m?.bodyLenToHeight); let bellyDepthRatio=num(m?.bellyDepthRatio); let hockAngleDeg=num(m?.hockAngleDeg); let rumpSlope=num(m?.rumpSlope); let toplineDeviation=num(m?.toplineDeviation); if(!Number.isFinite(bodyLenToHeight)) bodyLenToHeight=1.55; bodyLenToHeight=clamp(bodyLenToHeight,1.05,2.3); if(!Number.isFinite(bellyDepthRatio)) bellyDepthRatio=0.58; if(bellyDepthRatio>1 && bellyDepthRatio<=100) bellyDepthRatio/=100; bellyDepthRatio=clamp(bellyDepthRatio,0.25,1.05); if(!Number.isFinite(hockAngleDeg)) hockAngleDeg=145; hockAngleDeg=clamp(hockAngleDeg,110,180); if(Number.isFinite(rumpSlope)){ if(Math.abs(rumpSlope)>1 && Math.abs(rumpSlope)<=40) rumpSlope/=100; } else rumpSlope=0.06; rumpSlope=clamp(rumpSlope,-0.35,0.35); if(Number.isFinite(toplineDeviation)){ if(toplineDeviation>1 && toplineDeviation<=60) toplineDeviation/=100; } else toplineDeviation=0.06; toplineDeviation=clamp(toplineDeviation,0,0.6); return { bodyLenToHeight, bellyDepthRatio, hockAngleDeg, rumpSlope, toplineDeviation }; }
function estimateBCS({bellyDepthRatio,toplineDeviation,rumpSlope}){ let base=3; if(Number.isFinite(bellyDepthRatio)){ if(bellyDepthRatio<0.45) base-=0.9; else if(bellyDepthRatio>0.65) base+=0.7; } if(Number.isFinite(toplineDeviation)){ if(toplineDeviation>0.12) base-=0.6; if(toplineDeviation<0.04) base+=0.2; } if(Number.isFinite(rumpSlope) && rumpSlope>0.12) base-=0.2; return Math.max(1, Math.min(5, Number(base.toFixed(1)))); }
function flagsFromMetrics({hockAngleDeg,toplineDeviation,rumpSlope},bcs){ const flags=[]; if(Number.isFinite(hockAngleDeg)){ if(hockAngleDeg<135) flags.push('hock_angle_closed'); else if(hockAngleDeg<145) flags.push('hock_angle_watch'); } if(Number.isFinite(toplineDeviation) && toplineDeviation>0.12) flags.push('topline_curved'); if(Number.isFinite(rumpSlope) && rumpSlope>0.15) flags.push('steep_rump'); if(Number.isFinite(bcs) && bcs<2.2) flags.push('underweight'); return flags; }
function scoreFattening({metrics,bcs,sex,ageMonths,category}){ let score=0,totalW=0; if(Number.isFinite(bcs)){ const dist=Math.abs(bcs-3.0); let s=100-clamp(dist*50,0,100); const w=0.34; score+=s*w; totalW+=w; } if(Number.isFinite(metrics?.bodyLenToHeight)){ let s=100-Math.abs(metrics.bodyLenToHeight-1.65)*200; s=clamp(s,0,100); const w=0.18; score+=s*w; totalW+=w; } if(Number.isFinite(metrics?.hockAngleDeg)){ let s=100-Math.abs(metrics.hockAngleDeg-145)*6; s=clamp(s,0,100); const w=0.18; score+=s*w; totalW+=w; } if(Number.isFinite(metrics?.toplineDeviation)){ let s=100-clamp((metrics.toplineDeviation-0.08),0,0.5)*(100/0.5); s=clamp(s,0,100); const w=0.16; score+=s*w; totalW+=w; } if(Number.isFinite(metrics?.rumpSlope)){ let x=Math.abs(metrics.rumpSlope); let s=100-clamp(Math.max(0,x-0.12),0,0.35)*(100/0.35); s=clamp(s,0,100); const w=0.08; score+=s*w; totalW+=w; } if(Number.isFinite(ageMonths)){ let adj=1; if(category==='novillo'){ if(ageMonths<8||ageMonths>30) adj=0.9; } else if(category==='ternero'){ adj=0.85; } else if(category==='vaquilla'||category==='vaca_descarte'){ adj=0.88; } else if(category==='toro'){ adj=0.82; } const w=0.06; score+=100*adj*w; totalW+=w; } return clamp(Math.round(score/totalW),0,100); }
const BAND_ORDER=['Muy malo','Malo','Regular','Bueno','Excelente']; function bandFromScore(score){ if(score>=90) return 'Excelente'; if(score>=72) return 'Bueno'; if(score>=58) return 'Regular'; if(score>=45) return 'Malo'; return 'Muy malo'; } function minBand(a,b){ return BAND_ORDER[Math.min(BAND_ORDER.indexOf(a),BAND_ORDER.indexOf(b))]; }
function guardBand({bcs,emaciation,healthFlags,diseaseFindings,category,sex,ageMonths}){ let cap='Excelente'; if(Number.isFinite(bcs)&&bcs<2.2) cap=minBand(cap,'Muy malo'); else if(Number.isFinite(bcs)&&bcs<2.6) cap=minBand(cap,'Malo'); if(emaciation===true) cap=minBand(cap,'Muy malo'); const risky=['cojera','claudicación','tos','descarga nasal','diarrea','herida','bloat','timpanismo']; if(Array.isArray(diseaseFindings)&&diseaseFindings.some(x=> typeof x==='string' && risky.some(rx=> x.toLowerCase().includes(rx)))) cap=minBand(cap,'Malo'); if(Array.isArray(healthFlags)&&healthFlags.includes('hock_angle_closed')) cap=minBand(cap,'Malo'); if(category==='toro' && Number.isFinite(ageMonths) && ageMonths>30) cap=minBand(cap,'Regular'); return cap; }
function explanationFromHeur(m,bcs,verdict){ const bits=[]; if(Number.isFinite(m?.bodyLenToHeight)) bits.push(`Relación largo/alzada de ${m.bodyLenToHeight.toFixed(2)}.`); if(Number.isFinite(m?.hockAngleDeg)) bits.push(`Ángulo de corvejón ~${Math.round(m.hockAngleDeg)}°.`); if(Number.isFinite(m?.toplineDeviation)) bits.push(`Línea superior (desv. ${m.toplineDeviation.toFixed(2)}).`); if(Number.isFinite(bcs)) bits.push(`BCS ${bcs.toFixed(1)}.`); return `Veredicto ${verdict}. ${bits.join(' ')}`; }
function heuristic(){ const morphology={bodyLenToHeight:1.55,bellyDepthRatio:0.58,hockAngleDeg:142,rumpSlope:0.07,toplineDeviation:0.06}; const bcs=3.1; const sex='macho',categoryGuess='novillo',ageGuessMonths=18,weightGuessKg=320; const score=72, verdictBand='Bueno'; return {source:'heuristic',morphology,bcs,breedGuess:[{breed:'Brahman / Cebú',pct:40}],healthFlags:[],sex,categoryGuess,ageGuessMonths,weightGuessKg,score,verdictBand,explanation:explanationFromHeur(morphology,bcs,verdictBand)}; }

export default async function handler(req,res){
  setCORS(res); if(req.method==='OPTIONS') return res.status(204).end();
  try{
    if(req.method!=='POST') return res.status(405).json({error:'Use POST'});
    let body=req.body; if(typeof body==='string'){ try{ body=JSON.parse(body||'{}'); }catch{ body={}; } }
    const imageDataUrl=body?.imageDataUrl; if(!imageDataUrl) return res.status(400).json({error:'Missing imageDataUrl'});
    const key=process.env.OPENAI_API_KEY; const model=process.env.OPENAI_MODEL||'gpt-4o-mini';
    if(!key) return res.status(200).json(heuristic());
    const sys=`Devuelve SOLO JSON: morphology {bodyLenToHeight,bellyDepthRatio,hockAngleDeg,rumpSlope,toplineDeviation}, bcs, breedGuess[], healthFlags[], diseaseFindings[], sex, categoryGuess, ageGuessMonths, weightGuessKg, explanation_es.`;
    const user="Analiza morfología, BCS, sexo/categoría, edad/peso. Escribe explicación en español con números. Devuelve SOLO JSON.";
    const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify({model,temperature:0.2,response_format:{type:'json_object'},messages:[{role:'system',content:sys},{role:'user',content:[{type:'text',text:user},{type:'image_url',image_url:{url:imageDataUrl,detail:'low'}}]}]})});
    const txt=await r.text();
    if(!r.ok){ return res.status(200).json(heuristic()); }
    let data; try{ data=JSON.parse(txt);}catch{ return res.status(200).json(heuristic()); }
    let out=null; try{ out=JSON.parse(data?.choices?.[0]?.message?.content || '{}'); }catch(e){ out=null; }
    if(!out) return res.status(200).json(heuristic());
    const morph=sanitizeMetrics(out.morphology||{}); let bcs=num(out.bcs); if(!Number.isFinite(bcs)||bcs<1||bcs>5) bcs=estimateBCS(morph);
    return res.status(200).json({source:'openai',morphology:morph,bcs,breedGuess:out.breedGuess||[],healthFlags:out.healthFlags||[],sex:out.sex||'desconocido',categoryGuess:out.categoryGuess||'desconocido',ageGuessMonths:out.ageGuessMonths||null,weightGuessKg:out.weightGuessKg||null,score:70,verdictBand:'Regular',explanation:out.explanation_es||'Evaluación generada.'});
  }catch(err){ return res.status(200).json(heuristic()); }
}
